
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int pnt = 5;
  public static final int id = 12;
  public static final int cadena = 13;
  public static final int digito = 11;
  public static final int or = 7;
  public static final int EOF = 0;
  public static final int kleen = 4;
  public static final int error = 1;
  public static final int parc = 9;
  public static final int e_r = 10;
  public static final int porc = 2;
  public static final int pyc = 6;
  public static final int para = 8;
  public static final int igual = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "porc",
  "igual",
  "kleen",
  "pnt",
  "pyc",
  "or",
  "para",
  "parc",
  "e_r",
  "digito",
  "id",
  "cadena"
  };
}

